demo1/urls.py
from django.urls import path
from demo1 import views
urlpatterns=[
    path('insert/',views.insert,name='insert'),
    path('select/',views.select,name='select'),
    path('update/',views.update,name='update'),
    path('update_value/<sid>/',views.update_value,name='update_value'),
    path('delete/',views.delete,name='delete'),
    path('delete_value/<sid>/',views.delete_value,name='delete_value'),
]

pro6/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo1/',include('demo1.urls')),
]

demo1/models.py
from django.db import models
class student(models.Model):
    sid = models.AutoField(primary_key=True)
    sname=models.CharField(max_length=150)
    marks=models.IntegerField(null=True)
    doj=models.DateField(default="1995-06-06")
    
class sample(models.Model):
    sid1=models.IntegerField()
    sid2=models.BigAutoField(primary_key=True)
    sid3=models.BigIntegerField()
    sid4=models.FloatField()
    sid5=models.DecimalField(decimal_places=5,max_digits=5)
    sid6=models.DurationField()
    sname3=models.BooleanField()
    ip=models.GenericIPAddressField()
    ip1=models.BinaryField()
    
    date1=models.DateField()
    date2=models.DateTimeField()
    date3=models.TimeField()
    
    sname=models.CharField(max_length=150)
    sanme1=models.URLField(max_length=150)
    sname2=models.UUIDField(max_length=150)
    email=models.EmailField(max_length=150)
    img=models.ImageField()
    
    

demo1/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from demo1.models import student
# Create your views here.
def insert(request):
    if request.method=="POST":
        sname =request.POST['sname']
        marks= request.POST['marks']
        doj= request.POST['doj']
        print(sname,marks,doj)
        student.objects.create(sname=sname,marks=marks,doj=doj)
        #return HttpResponse('insert')
        return redirect('select')
    return render(request,'insert.html')


def select(request):
    res=student.objects.all()
    return render(request,'select.html',{'res':res})


def update(request):
    if request.method=='POST':
        sid= request.POST['sid']
        res=student.objects.filter(sid=sid)
        return render(request,'update.html',{'res':res})
    return render(request,'update.html')

def update_value(request,sid):
    if request.method=="POST":
        sname =request.POST['sname']
        marks= request.POST['marks']
        doj= request.POST['doj']
        print(sname,marks,doj)
        res=student.objects.filter(sid=sid).update(sname=sname,marks=marks,doj=doj)
        #return HttpResponse('update')
        return redirect('select')
    return render(request,'insert.html')


def delete(request):
    if request.method=='POST':
        sid= request.POST['sid']
        res=student.objects.filter(sid=sid)
        return render(request,'delete.html',{'res':res})
    return render(request,'delete.html')

def delete_value(request,sid):
    if request.method=="POST":
        res=student.objects.filter(sid=sid).delete()
        #return HttpResponse('update')
        return redirect('select')
    

demo1/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% if res %}
    {%for i in res%}
    <form method="post" action="{% url 'delete_value' sid=i.sid %}">
        
        {% csrf_token %}
        <input type="text" id="id_sname" name="sname" value="{{i.sname}}" required><br>
        <input type="text" id="id_marks" name="marks" value="{{i.marks}}"required><br>
        <input type="text" id="id_doj" name="doj" value="{{i.doj}}" required><br>
        <input type="submit" value="delete">
        </form>
        {% endfor %}
    {% else %}
    <form method="post">
        {% csrf_token %}
        <input type="text" id="id_sid" name="sid" required><br>
        <input type="submit" value="delete">
        </form>
    {% endif  %}
</body>
</html>

demo1/templates/insert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <input type="text" id="id_sname" name="sname" required><br>
        <input type="text" id="id_marks" name="marks" required><br>
        <input type="text" id="id_doj" name="doj" placeholder="yyyy-mm-dd" required><br>
        <input type="submit" value="insert">
        </form>

        <a href="{% url 'select' %}"><button>select</button></a>
</body>
</html>

demo1/templates/select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border=2>
        <tr><td>SID</td><td>sname</td><td>marks</td><td>doj</td></tr>
        {% for i in res %}
        <tr><td>{{i.sid}}</td><td>{{i.sname}}</td><td>{{i.marks}}</td><td>{{i.doj}}</td></tr>
        {% endfor %}
    </table>

    <a href="{% url 'insert' %}"><button>insert</button></a>
    <a href="{% url 'update' %}"><button>update</button></a>
    <a href="{% url 'delete' %}"><button>delete</button></a>
</body>
</html>

demo1/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% if res %}
    {%for i in res%}
    <form method="post" action="{% url 'update_value' sid=i.sid %}">
        
        {% csrf_token %}
        <input type="text" id="id_sname" name="sname" value="{{i.sname}}" required><br>
        <input type="text" id="id_marks" name="marks" value="{{i.marks}}"required><br>
        <input type="text" id="id_doj" name="doj" value="{{i.doj}}" required><br>
        <input type="submit" value="update">
        </form>
        {% endfor %}
    {% else %}
    <form method="post">
        {% csrf_token %}
        <input type="text" id="id_sid" name="sid" required><br>
        <input type="submit" value="update">
        </form>
    {% endif  %}
</body>
</html>